### PR TITLE
Minor copy edits and updates

### PR DESCRIPTION
**Pull request by allenfear**

### CODE REVIEW

**Review by stovak — APPROVED** [review]

**Comment by stovak** [comment]
Hey, we're not going to update the 1.x version anymore. 8.X branch is where all the cool kids are workin things out.

**Review by stovak — APPROVED** [review]

**Comment by stovak** [comment]
@allenfear I rebased around 8.x and fixed the conflicts. Please make sure I didn't step on any of your changes before I merge in.

**Comment by allenfear** [comment]
@stovak sorry about that. Happy to join the cool kids in the right branch. It also looks like the checks failed. If it is easier, you can just close this and I can resubmit the PR against the right branch. Whatever's easiest for you.

**Comment by stovak** [comment]
Closed. Plz resubmit against the 8.x branch.

**Pull request closed without merging**
